# Generated by Django 3.1.5 on 2021-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20210220_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Add the original URL that you want to shorten.')),
                ('key', models.CharField(help_text='Add any random characters of your choice to shorten it.', max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
